name: "Clean Up Workspace"

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Which workspace you want to delete?'
        required: true
        type: string
        default: 'test'
  push:
    branches:
      - '**'

jobs:
  clean-up-workspace:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out PR Branch Git History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #You're trying to parse the git log to find the parent branch — but on GitHub runners, the Git history is shallow by default (depth = 1), which may break git log.

      - name: Set Environment Variable Only on Push
        if: github.event_name == 'push'
        run: |
          echo "WORKSPACE_NAME=test" >> $GITHUB_ENV

      - name: Delete Git Branch in Github
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          REPO: ${{ github.repository }}
        run: |
          echo "Attempting to delete branch: $WORKSPACE_NAME from $REPO"

          # URL encode the branch name (in case of slashes)
          ENCODED_BRANCH=$(jq -rn --arg b "$WORKSPACE_NAME" '$b|@uri')
          
          # Perform DELETE request to GitHub REST API
          response=$(curl -s -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/git/refs/heads/$ENCODED_BRANCH")

          if [ "$response" -ne 204 ]; then
            echo "Failed to delete branch in Github. HTTP status: $response"
            exit 1
          fi

