name: "Clean Up Workspace"

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Which workspace you want to delete?'
        required: true
        type: string
        default: 'test'
  push:
    branches:
      - '**'

jobs:
  clean-up-workspace:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out PR Branch Git History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #You're trying to parse the git log to find the parent branch — but on GitHub runners, the Git history is shallow by default (depth = 1), which may break git log.

      - name: Set Environment Variable Only on Push
        if: github.event_name == 'push'
        run: |
          echo "WORKSPACE_NAME=test" >> $GITHUB_ENV

      - name: Delete Git Branch in GitHub
        env:
            GITHUB_TOKEN: ${{ github.token }}
            REPO: ${{ github.repository }}
            WORKSPACE_NAME: ${{ env.WORKSPACE_NAME }}
        run: |
            echo "Attempting to delete branch: $WORKSPACE_NAME from $REPO"

            # URL encode the branch name
            ENCODED_BRANCH=$(jq -rn --arg b "$WORKSPACE_NAME" '$b|@uri')

            # Temp file for response
            RESPONSE_FILE=$(mktemp)

            # Make API call and capture HTTP status
            HTTP_STATUS=$(curl -s -o "$RESPONSE_FILE" -w "%{http_code}" -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/git/refs/heads/$ENCODED_BRANCH")

            if [ "$HTTP_STATUS" -eq 204 ]; then
            echo "✅ Branch '$WORKSPACE_NAME' deleted successfully."
            else
            echo "❌ Failed to delete branch. HTTP status: $HTTP_STATUS"
            if [ -s "$RESPONSE_FILE" ]; then
                echo "Response from GitHub:"
                cat "$RESPONSE_FILE"
            else
                echo "No response body returned."
            fi
            exit 1
            fi

